name: TappyPlane
canvasWidth: 1280
canvasHeight: 720
scalingMode: letterbox
textureStrategy: resize
vsync: true
windowMode: windowed
windowWidth: 1280
windowHeight: 720
windowResizable: true
luaDir: .
web:
  resizeCanvasToWindow: false
startSceneId: 1
scenes:
  - filepath: Main Scene.scene
  - filepath: HUD Scene.scene
